// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHHLArRfNY2k0Uw74CpOJL1MiLujbHGX8',
    appId: '1:754150768955:web:58637007edc3166fa3771e',
    messagingSenderId: '754150768955',
    projectId: 'mtuconnecthub',
    authDomain: 'mtuconnecthub.firebaseapp.com',
    storageBucket: 'mtuconnecthub.firebasestorage.app',
    measurementId: 'G-FPZV7KJ4D5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrcS0xMOPzwA4tD5Z3-ahSIK1oi8B9Y-E',
    appId: '1:754150768955:ios:41ea2e08079e262ba3771e',
    messagingSenderId: '754150768955',
    projectId: 'mtuconnecthub',
    storageBucket: 'mtuconnecthub.firebasestorage.app',
    iosBundleId: 'com.example.mtuConnectHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHHLArRfNY2k0Uw74CpOJL1MiLujbHGX8',
    appId: '1:754150768955:web:725b82db50f3f094a3771e',
    messagingSenderId: '754150768955',
    projectId: 'mtuconnecthub',
    authDomain: 'mtuconnecthub.firebaseapp.com',
    storageBucket: 'mtuconnecthub.firebasestorage.app',
    measurementId: 'G-SMJGMF26XJ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrcS0xMOPzwA4tD5Z3-ahSIK1oi8B9Y-E',
    appId: '1:754150768955:ios:41ea2e08079e262ba3771e',
    messagingSenderId: '754150768955',
    projectId: 'mtuconnecthub',
    storageBucket: 'mtuconnecthub.firebasestorage.app',
    iosBundleId: 'com.example.mtuConnectHub',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByHJ59fTV7A5TxUyiu3rdbwpKcTWQ0CM4',
    appId: '1:754150768955:android:23468da86364258ca3771e',
    messagingSenderId: '754150768955',
    projectId: 'mtuconnecthub',
    storageBucket: 'mtuconnecthub.firebasestorage.app',
  );

}